--ESPECIFICAÇÃO
create or replace package PKG_CALCULADORA IS
    PROCEDURE CALCULA_REAJUSTE(SALARIO_ATUAL IN NUMBER);
    FUNCTION CAL_CAMBIO(VL_DOL NUMBER)
        RETURN NUMBER;
END PKG_CALCULADORA;
/
--CORPO(BODY)
CREATE OR REPLACE PACKAGE BODY PKG_CALCULADORA IS 
    PROCEDURE CALCULA_REAJUSTE(SALARIO_ATUAL IN NUMBER) IS
        VL_SALARIO_REAJUSTADO NUMBER(8,2);
    BEGIN 
        VL_SALARIO_REAJUSTADO := SALARIO_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SÁLARIO ATUAL - R$: ' || SALARIO_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SÁLARIO REAJUSTADO - R$: ' || VL_SALARIO_REAJUSTADO);
        END CALCULA_REAJUSTE;

        FUNCTION CAL_CAMBIO(VL_DOL IN NUMBER) RETURN NUMBER IS
            VL_CAMBIO NUMBER (8,2);
        BEGIN 
            VL_CAMBIO := VL_DOL * 5.04;
            DBMS_OUTPUT.PUT_LINE('SÁLARIO ATUAL - R$: ' || VL_DOL);
            DBMS_OUTPUT.PUT_LINE('SÁLARIO REAJUSTADO - R$: ' || VL_CAMBIO);
            END CAL_CAMBIO;
END PKG_CALCULADORA;

